### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by maverick74** [zluca/Sidebar#11]
Hi again,

My friend is having performance problems with the sidebar (i'm not using it at the moment). He says that without any other addons active, it freezes Firefox. As soon as he disables the addon and reopens the same tabs it all works well.

I'm attaching the screenshot he sent me
![imgpsh_fullsize](https://user-images.githubusercontent.com/14912461/34670994-81198028-f470-11e7-8f3b-e7e50aa3a3ce.jpg)

He also says it interfers with other addons, but i have my doubts about that point (specially because he can't say exactly what the problem is). I think it may all came from the same problem

**Comment by zluca** [comment]
I had same things sometimes (Firefox only), but unfortunately this is hard to reproduce. So I changed code that can be responsible to this freezes. Let see if 4.10 fix this (it should be tomorrow).

**Comment by Merlignux** [comment]
Well, i've got no complaints so far from my friend so far :) Probably fixed...

(personally, i'm not having troubles with it... but i was not complaining before either, so i'm suspicious!)

**Comment by maverick74** [comment]
Well, i've got no complaints so far from my friend so far :) Probably fixed...

(personally, i'm not having troubles with it... but i was not complaining before either, so i'm suspicious!)

**Comment by zluca** [comment]
> Probably fixed...
Unfortunately not. But freezes are now weaker so owners of powerful PCs doesnt feel them.

**Comment by zluca** [comment]
@maverick74 
I doesn't see performance problem since 0.4.13 so i guess it has been fixed during code refactor.

**Comment by Merlignux** [comment]
nice :)

tks
