### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by vultureg7** [zluca/Sidebar#14]
Would it be possible to add an option for the sidebar to be closed only after the thinbar has been clicked? Many times I accidentally pull the mouse away and it vanishes and have to get to the edge again. Click to open-click to close would be preferable to me as an option. Many thanks!

**Comment by zluca** [comment]
Ok. I have to think how to implement this feature in next release.

**Comment by vultureg7** [comment]
Thx! :)

**Comment by zluca** [comment]
@vultureg7 
Closed in 0.5.5
