### ISSUE TITLE
FR: fonts/elements sizes – how to change?

### ISSUE THREAD

**Issue by beelze** [zluca/Sidebar#19]
![sbarplus](https://user-images.githubusercontent.com/5619507/40140273-57920586-5974-11e8-8ba5-8080bc2a59be.png)

In my case, both buttons and text sizes are **too** large. And there is no option to change it.

**Comment by zluca** [comment]
> And there is no option to change it.

You are wrong. There is.
Options > Theme > Font  size
Icons and other elements would resize together with fonts.
