### ISSUE TITLE
After browser restarts its losing all saved settings..

### ISSUE THREAD

**Issue by StV0911** [zluca/Sidebar#3]
Hi zluca,

as i already mentioned on the Firefox add-on website: "reviews"...:
After browser restarts its still losing all the saved settings also with version 0.3.4
macOS High Sierra - FF 58.0b6 (64-bit)

Big thanks for sharing your good work !

**Comment by zluca** [comment]
Ok. 0.3.5 version is uploaded to AMO. I hope it will stop this annoying bug. Plz test when Mozilla approved new version.

**Comment by StV0911** [comment]
@zluca 

i tested 0.3.5 mow with different settings for make sure that the bug is not bounded to a special setting like for example sidebar on the right or left side or in window mode.. a.s.o..

Now,
The add-on remembers well the settings/setup on the extensions page like "services and theme" and all the others seems to work well. 

Next, i tested the sidebar if it will remember which bookmarks-folders i closed and which i opened (remember last position and open/closed folders.)..
But when i restart, "all bookmark-folders" are open again and it does not remember the last used opened and closed bookmarks...  I hope you understand what i mean..

**Comment by zluca** [comment]
> I hope you understand what i mean..

Yep. For now all folders except rss recreated at startup. This will be changed in future versions.

**Comment by StV0911** [comment]
You are very welcome..!!
Keep on going
and big thanks to you..!!!
