### ISSUE TITLE
Only show tabs from active window in tree view

### ISSUE THREAD

**Issue by Su-Well** [zluca/Sidebar#30]
I think a separate option for only showing tabs from active window in tree view would be great. I'm 75% done implementing this myself ([here](https://github.com/Su-Well/Sidebar/tree/windowed_tree)), but as explained in the commit message I didn't quite finish it.

It'd be awesome if you'd like to fix my mistakes and add it to your repo @zluca 🙂

**Comment by zluca** [comment]
Handling tabs from different windows are pain in the ass from the beginning of add-on. So I would rework it totally.
