### ISSUE TITLE
Add an option for limiting the number of levels displayed in tree views

### ISSUE THREAD

**Issue by Su-Well** [zluca/Sidebar#31]
Personally I find that anything more than one level has limited value, so I'd like to restrict it to one level.

Here's an example of a tree view with many levels: 
![image](https://user-images.githubusercontent.com/22740286/46590261-3101ef80-cab2-11e8-91b5-657c1816e283.png)

**Comment by zluca** [comment]
It is probably can be done with css only. I look into this later.
