### ISSUE TITLE
Cannot show whole page for some sites

### ISSUE THREAD

**Issue by 0w0miki** [zluca/Sidebar#4]
After using this addon, page of https://ticktick.com/#q/all/tasks does not display completly.
With sidebar+ page shows like the following pic.
![using sidebar+](https://raw.githubusercontent.com/0w0miki/markdownphoto/note/Screenshot-2017-12-2%20All%20-%20TickTick(2).png)
While it should look like this.
![sidebar+ banned](https://raw.githubusercontent.com/0w0miki/markdownphoto/note/Screenshot-2017-12-2%20All%20-%20TickTick(1).png)
It seems height of some elements becomes 0 after the addon is used.

tested on Nightly 59 and Firefox 57

**Comment by zluca** [comment]
@0w0miki 
Thx for reporting. Can you confirm this bug in Chromium?

**Comment by 0w0miki** [comment]
I just updated to version 0.3.8. Now everything is ok both in firefox and chromium.

**Comment by zluca** [comment]
Glad to hear that. Closed.
