### ISSUE TITLE
Problem with RSS

### ISSUE THREAD

**Issue by adr1um** [zluca/Sidebar#41]
В общем, после подписки на rss все замечательно работает до тех пор, пока не закроешь/откроешь браузер, как тут же подписка слетает. Приходится заново подписываться и не закрывать браузер)
p.s. Спасибо за замечательнейшее дополнение.

**Comment by zluca** [comment]
@adr1um 
А что за браузер то? У меня и в файрфоксе и в хромиуме всё работает.

**Comment by adr1um** [comment]
Firefox последний.. ну да, так-то странно, раз только у меня этот "баг" появился, значит, проблема на моей стороне. Буду разбираться.
Кстати, в качестве предложения - может, есть возможность добавить импорта/экспорта настроек дополнения? Было бы удобно.

**Comment by adr1um** [comment]
Записал видео, как это выглядит. Может, есть возможность отослать какую-нибудь нужную отладочную информацию? 
https://youtu.be/lpcMCplG8-E

**Comment by zluca** [comment]
Откройте консоль ctrl+shift+J. Там могут быть что-то полезное. И если не трудно проверьте в Хроме.

**Comment by adr1um** [comment]
В хроме работает.
Извините, не знаю, как перенести разметку и не похерить ее, так что, сделал скриншот, ну и сам текст ошибок:

![untitled](https://user-images.githubusercontent.com/37171278/48669931-b3ed7f80-eb1f-11e8-9856-bb92669a1559.png)


`
Unchecked lastError value: Error: can't assign to property "readed" on false: not an object sidebar.js:1
U
moz-extension://6338ecae-0a23-478a-a5a1-3fe1f91d6376/sidebar.js:1:29417

Promise resolved while context is inactive
dialog.js:1
l
moz-extension://6338ecae-0a23-478a-a5a1-3fe1f91d6376/dialog.js:1:292

ReferenceError: fav is not defined background.js:1:52920
p/p.onreadystatechange
moz-extension://6338ecae-0a23-478a-a5a1-3fe1f91d6376/background.js:1:52920

Unchecked lastError value: Error: Promised response from onMessage listener went out of scope startpage.js:1
O
moz-extension://6338ecae-0a23-478a-a5a1-3fe1f91d6376/startpage.js:1:14888


TypeError: this.sidebars.get(...) is undefined  browser-sidebar.js:437:26 `

**Comment by adr1um** [comment]
И да, я отключал все другие дополнения - все равно не работает, так что, думаю, дело не в конфликте

**Comment by zluca** [comment]
> Unchecked lastError value: Error: can't assign to property "readed" on false: not an object sidebar.js:1

Очень похоже на баг который я недавно пофиксил. К сожалению пока обнову выкатить не могу потому что паралельно наделал кучу других багов. Придётся подождать недельку-две. =)

**Comment by adr1um** [comment]
@zluca 
Окей, тогда подожду) Спасибо за оперативную помощь =)

**Comment by zluca** [comment]
@adr1um 
В 0.6.0 лучше не стало?

**Comment by zluca** [comment]
Судя по молчанию топик стартера оно или пофикшено или уже не надо. Закрываю. =)
