### ISSUE TITLE
Bookmarks Folders view

### ISSUE THREAD

**Issue by PavelPMarts** [zluca/Sidebar#49]
Hi guys,

I found your sidebar very useful, but mostly for Tabs. Unfortunately I can't find a possibility to turn on the folders view for the bookmarks.

Do you have such a feature?

Kind regards, Pavel.

**Comment by zluca** [comment]
Bookmarks turns into folders view automatically if the county of bookmarks not more than allowed in options (1999 by default). You can found this option in Misc section.

However, you are not the first one who ask about this. So this would be redesigned in the next releases.

**Comment by zluca** [comment]
Since 0.6.6 bookmarks are always in tree view.
