### ISSUE TITLE
Option to keep original Bookmark structure 

### ISSUE THREAD

**Issue by maverick74** [zluca/Sidebar#5]
Please add an option to keep original Bookmark Structure / Tree

**Comment by zluca** [comment]
It should be tree. Until you reach the limit (999 by default). You can raise the limit, but it can hurt performance.

**Comment by maverick74** [comment]
ups... i have more than 2000 bookmarks ':\ 
It's been years keeping important stuff... LOL

**Comment by zluca** [comment]
Thx you for report anyway. I will have to think how to warn users when bookmarks is too many. But it can wait.

**Comment by maverick74** [comment]
@zluca i have a friend that keeps complaining that:

1. the order of the bookmarks are not the one he sets (it is reset after each restart)
2. bookmark folders are always expanded (and when one has a lot of them this is not a good thing!)

Do you prefer i open a new issue for each of the complaints or reporting here is ok?

**Comment by zluca** [comment]
1. This is definitely a bug.
2. And this has to be fixed in 0.3.9. Did your friend use last version?

The sense of issues is to give me feedback, an you already did it.

**Comment by maverick74** [comment]
Yes, i believe so! 

Still i'll ask for him to make sure he as the latest version

**Comment by maverick74** [comment]
Ok!!! He did not have the latest version. In 0.3.10 it's fixed and working ok.

However, 1. is still needing a fix

**Comment by maverick74** [comment]
@zluca 
With the recent release Bookmarks can already be rearranged ( THANKS A LOT!!! :) ) 
However there is still problems with the folders.
They are not on their original order and cannot be arranged (from what i understood)

Also, is it possible to have an option that, when the sidebar is hiding and on it's "thin form", instead of touching the leftside of the screen one have to left-click on its border (this to avoid open it unintentionally)?

**Comment by zluca** [comment]
This is strange because for me bookmarks folders arranged correctly both on Firefox and Chromium.
> is it possible

It is possible. But i made decision to move all new features into new 0.4 branch. And 0.3 now is only for bugfixes and small thing. So it takes week or two before you can see requested stuff.

**Comment by maverick74** [comment]
Sorry for taking so long.

I just clarified the problems over phone!

I explained it badly - **sorry**! The problems are that:
1. folders cannot be re-arranged and 
2. they cannot be positioned between regular bookmarks

e.g.: about 2.
b=bookmark f=folder

in bookmarks root folder, he has

_b1
b2
b3_
**f1**
_b4
b5_
**f2**
**f3**
_b6_

with the addon the order becames:
**f1**
**f2**
**f3**
_b1
b2
b3
b4
b5
b6_

(_please notice i did not tested this myself! where i am i do not have the addon installed_)

**Comment by zluca** [comment]
Ok, now I see the problem. Should be fixed in 0.4.

**Comment by zluca** [comment]
@maverick74 
0.4.2 uploaded to AMO. It should fix everything.

**Comment by maverick74** [comment]
Great!!!

Thank You!

Let me ask something i know i'll get asked about: Is left-clicking on the sidebar's border to open it (instead of touching it with the mouse) arriving soon as well?

**Comment by zluca** [comment]
> left-clicking
Yep. This feature in the list.
