### ISSUE TITLE
Multi-columns, search tab and issue with reopen 

### ISSUE THREAD

**Issue by Pfedj** [zluca/Sidebar#52]
1. Is it possible to make several columns for displaying tabs? The width of the columns is fixed. Filling the table with new tabs can be in rows or lines.
2. Is it possible to make a search bar to search in open tabs? In the future it is possible to expand the search for bookmarks and history. Add support for simplest regular expressions to search.
3. It looks like there is a bug. If you close / open the application, the ability to collapse folders disappears when you group tabs by domain.

1 Это возможно сделать несколько колонок для отображения вкладок? Ширина колонок фиксирована. Заполнение таблицы новыми вкладками может быть по рядам или по строчкам. 
2 Возможно сделать панель поиска, чтобы искать в открытых вкладках? В дальнейшим возможно расширить поиск на закладки и журнал. Добавить поддержку простейших регулярных выражений для поиска.
3 Похоже есть баг. Если закрыть/ открыть приложение, то пропадает возможность сворачивать папки при группировки вкладок по домену.

Спасибо за классный плагин! Желаю удачи!

**Comment by zluca** [comment]
1. No.
2. Yes it is possible, I will make it later.
Bookmarks and history already has search.
Regular expressions are not supported because webExtensions API do not support it.
3. Can't reproduce this bug. :/
