### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by grahamperrin** [zluca/Sidebar#60]
There's no release note: 

![image](https://user-images.githubusercontent.com/192271/144685922-a479f222-0714-4ceb-8bad-3c581a3fb8a4.png)

<https://addons.mozilla.org/addon/sidebar_plus/versions/> | <https://addons.mozilla.org/addon/sidebar_plus/versions/0.6.14/updateinfo/> | <https://addons.mozilla.org/en-GB/firefox/addon/sidebar_plus/versions/0.6.14/updateinfo/> 

I see https://github.com/zluca/Sidebar/compare/3c8c3715a075827e7f8f963d2792100e25d64f2e...9ece8d1f9222d4e67424e9b13d20fa981a25cba6 for changes between 0.6.10 and 0.6.14 but please, can you _describe_ the changes? And publish at `addons.mozilla.org`.

Thanks

**Comment by zluca** [comment]
Ok i was add the notes, but it looks like Firefox only download it in the moment of update. You can see notes in the third link you posted, but not in about:addons page, at least i don't see it there.

I also post it here:
> Building process was changed in order to new AMO rules. Now there is no code minification used what lead to bigger package size.
Also integration with Pocket removed due to it is buggy.

**Comment by grahamperrin** [comment]
Thanks, incidentally history before 0.6.14 has disappeared from https://addons.mozilla.org/en-GB/firefox/addon/sidebar_plus/versions/
