### ISSUE TITLE
Ubuntu 20.04 LTS, Firefox 96 Sidebar empty

### ISSUE THREAD

**Issue by Olfried2** [zluca/Sidebar#61]
Hello, 
in the already described environment, the sidebar is empty. I already did the following

- opened closend firefox,
- put sidebar to the other side
- opened window, iframe
- disabled, enabled
- restart machine
- delete cookies

sidebar keeps empty. 
bookmarks and history (that's what I use) will be filled with content.
I'm not sure if there was an update of firefox or something else today (security updates are always on)
Maybe something happened when I openend "outlook.office.com" that was the moment the sidebar 
"cleared". Any idea what to do?
Thanks in advance

**Comment by zluca** [comment]
`Any idea what to do?`
Try to delete extension completely and then reinstall it.

**Comment by Olfried2** [comment]
Zluca, thanks for this hint (could have tried it by myself :) )
Problem resolved
